### User sign up endpoint
POST http://localhost:5000/v1/user HTTP/1.1
Content-Type: application/json

{
    "name": "Kay Shoks",
    "company": "Paz Carrus",
    "address": "Dallas TX",
    "phone": "08012345678",
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret456"
}

### User sign in endpoint
POST http://localhost:5000/v1/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret123"
}

### Get user profile
GET http://localhost:5000/v1/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sdV9zaG9rc0BwYXpjYXJydXMub3JnIiwiaWF0IjoxNjI2MjI0MDEzLCJleHAiOjE2MjYyMjQ5MTN9.XqXSHIgm0JpL8IpMaF_0G05HPywgHTo2ApYY2ewPBy0

### Get refresh token endpoint
GET http://localhost:5000/v1/token/new-access-jwt HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sdV9zaG9rc0BwYXpjYXJydXMub3JnIiwiaWF0IjoxNjI2MTc3MDY4LCJleHAiOjE2MjYxNzc5Njh9.p6h20A1hDjkNknjs4dxRarN43NikfoSnrj1ne9l4ouQ

### Reset password endpoint
POST http://localhost:5000/v1/user/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org"
}

### Update password endpoing
PATCH http://localhost:5000/v1/user/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org",
    "pin": 880468,
    "newPassword": "secret246"
}

    

