### User sign up endpoint
POST http://localhost:5000/v1/user HTTP/1.1
Content-Type: application/json

{
    "name": "Kay Shoks",
    "company": "Paz Carrus",
    "address": "Dallas TX",
    "phone": "08012345678",
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret456"
}

### User sign in endpoint
POST http://localhost:5000/v1/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret456"
}

### Get user profile
GET http://localhost:5000/v1/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sdV9zaG9rc0BwYXpjYXJydXMub3JnIiwiaWF0IjoxNjI2MTcwNDUzLCJleHAiOjE2MjYxNzEzNTN9.gf5rR0TVk8DPA_YVEYaT7YFxRD7P8XHjC0MiPNETJZo

### Get refresh token endpoint
GET http://localhost:5000/v1/token/new-access-jwt HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sdV9zaG9rc0BwYXpjYXJydXMub3JnIiwiaWF0IjoxNjI2MDg5NDQzLCJleHAiOjE2Mjg2ODE0NDN9.hj7Gh4xaNlZoTZ8locv-FhJCS6AEdyjUmZKMCwJg_y4

### Reset password endpoint
POST http://localhost:5000/v1/user/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org"
}

### Update password endpoing
PATCH http://localhost:5000/v1/user/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org",
    "pin": 568259,
    "newPassword": "secret789"
}

    

