### User sign up endpoint
POST http://localhost:5000/v1/user HTTP/1.1
Content-Type: application/json

{
    "name": "Kay Shoks",
    "company": "Paz Carrus",
    "address": "Dallas TX",
    "phone": "08012345678",
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret456"
}

### User sign in endpoint
POST http://localhost:5000/v1/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "olu_shoks@pazcarrus.org",
    "password": "secret456"
}

### Get user profile
GET http://localhost:5000/v1/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9sdV9zaG9rc0BwYXpjYXJydXMub3JnIiwiaWF0IjoxNjI2MDg0MDg1LCJleHAiOjE2MjYwODQ5ODV9.5d8tkwt8m2H-Rpo18WW0DkkjAwLQ3eZRfqmcv8D5QRIgh
